// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBank.Domain.Models;

#nullable disable

namespace WebBank.Domain.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class BankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("WebBank.Domain.Models.AccountOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("CurrentAccountPlusId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAccountPlusId");

                    b.ToTable("AccountOperation");
                });

            modelBuilder.Entity("WebBank.Domain.Models.CurrentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasDiscriminator().HasValue("CurrentAccount");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebBank.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebBank.Domain.Models.CurrentAccountPlus", b =>
                {
                    b.HasBaseType("WebBank.Domain.Models.CurrentAccount");

                    b.HasDiscriminator().HasValue("CurrentAccountPlus");
                });

            modelBuilder.Entity("WebBank.Domain.Models.AccountOperation", b =>
                {
                    b.HasOne("WebBank.Domain.Models.CurrentAccountPlus", null)
                        .WithMany("Operations")
                        .HasForeignKey("CurrentAccountPlusId");
                });

            modelBuilder.Entity("WebBank.Domain.Models.CurrentAccount", b =>
                {
                    b.HasOne("WebBank.Domain.Models.User", null)
                        .WithMany("Accounts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("WebBank.Domain.Models.User", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("WebBank.Domain.Models.CurrentAccountPlus", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
